services:
  # Application container
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn start:dev
    env_file:
      - ./.env
    ports:
      - '3001:3001'
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    # depends_on:
      # - mongo
  # Mongodb database service
  # mongo:
    # image: mongo