version: '3'

services: 
  # backend:
  #   container_name: backend
  #   build: ./backend/dockerfile
  #   env_file: 
  #     - ./backend/.env
  #   ports: 
  #     - '${PORT}:${PORT}'
  #   volumes:
  #     - .:/backend
  mongo:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kingmanga